static_dir = "./static/"
log_dir = "/tmp/tts-logs"
instance_name = "tts"
authorized_ids = ["public_token"]

[modules.tts_py]
hf_repo = "data_moshi/model"
type = "Py"
path = "/api/tts_streaming"
# On pointe vers le tokenizer qu'on vient de télécharger
text_tokenizer_file = "data_moshi/model/tokenizer_spm_8k_en_fr_audio.model"
batch_size = 8
text_bos_token = 1

[modules.tts_py.py]
log_folder = "/tmp/moshi-server-logs"
# On pointe vers notre dossier de voix local
voice_folder = "data_moshi/voices"
# On définit notre voix téléchargée comme défaut
default_voice = "default_voice.wav"

# Paramètres de qualité
cfg_coef = 2.0
cfg_is_no_text = true
padding_between = 1
n_q = 24
padding_bonus = -1
