services:
  avatar:
    image: avatar
    build:
      context: ./Avatar
      dockerfile: ./Dockerfile
    ports:
      - "5003:5003"
    dns: # <--- AJOUTER CECI
      - 8.8.8.8 # Google DNS
      - 1.1.1.1
    volumes:
      - ./captures:/app/captures
    extra_hosts:
      - "host.docker.internal:host-gateway"

  faceapp:
    build:
      context: ./FaceRecognition
      dockerfile: ./python/Dockerfile
    image: faceapp:latest
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - INSIGHTFACE_PROVIDER=CPUExecutionProvider
    volumes:
      - ./FaceRecognition/insightface_models:/root/.insightface/models
      - ./captures:/app/captures
    privileged: true
    networks:
      - moshi_net
    ports:
      - "5006:5006"
    depends_on:
      - agent
    extra_hosts:
      - "host.docker.internal:host-gateway"

  stt:
    build:
      context: ./STT
      dockerfile: ./Dockerfile
    image: stt:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5007:5007"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./records:/app/records
      - ./cacheHuggingFace:/root/.cache/huggingface
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - "audio"
    gpus: all
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: moshi_mongo
    restart: always
    volumes:
      - mongo_data:/data/db # Persistance des données sur le disque
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - moshi_net
    ports:
      - "27017:27017"

  # ==========================================
  # LLM : ORCHESTRATEUR (Gateway / CPU)
  # ==========================================
  orchestrator:
    build: ./LLM/app
    container_name: cpe-orchestrator
    ports:
      - "8001:8001"
    environment:
      # Indique où trouver le cerveau (nom du service ci-dessus)
      - CPE_BRAIN_HOST=cpe-brain

      # Indique où trouver Moshi (host.docker.internal = votre machine physique)
      # Si Moshi est un autre conteneur, mettez son nom ici.
      - MOSHI_HOST=host.docker.internal
    extra_hosts:
      # Permet au conteneur de voir le localhost de votre machine Ubuntu
      - "host.docker.internal:host-gateway"
    depends_on:
      - cpe-brain
    networks:
      - cpe-network

  # ==========================================
  # LLM : CERVEAU (Intelligence / GPU)
  # ==========================================
  cpe-brain:
    build: ./TTS/api
    container_name: cpe-brain
    ports:
      - "8000:8000"
    volumes:
      # Vos documents pour le RAG
      - ../LLM/data:/data
      # La persistance de l'index vectoriel (pour ne pas réindexer à chaque fois)
      - ../LLM/vector_db:/vector_db
      # Cache HuggingFace pour ne pas retélécharger le modèle Mistral à chaque reboot
      - hf_cache:/root/.cache/huggingface
    environment:
      # Connexion à Mongo via le nom du service docker
      - MONGO_URI=mongodb://mongo:27017
      # - HUGGING_FACE_HUB_TOKEN=votre_token_huggingface_ici
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Utilise les 2 GPUs
              capabilities: [gpu]
    # Important pour vLLM en multi-GPU (mémoire partagée)
    ipc: host
    depends_on:
      - mongo
    networks:
      - cpe-network

  # --- TTS (Moshi) ---
  moshi:
    build: ./TTS/moshi
    container_name: moshi_server
    volumes:
      - moshi_data:/app/data_moshi # Persistance des modèles
    gpus: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - moshi_net

volumes:
  hf_cache:
  moshi_data:
  mongo_data:

networks:
  moshi_net:
  cpe-network:
    driver: bridge
