services:
  cpe-rag:
    build: .
    container_name: cpe_rag_service
    runtime: nvidia
    environment:
      - HUGGING_FACE_HUB_TOKEN=votre_token_hf_ici
      # Définit le cache des modèles dans un volume pour ne pas retélécharger à chaque fois
      - HF_HOME=/root/.cache/huggingface
    volumes:
      - ./data:/data              # Vos PDF
      - ./vector_db:/vector_db    # La base de données
      - hf_cache:/root/.cache/huggingface # Cache des modèles
    ports:
      - "8000:8000"
    gpus: all
    ipc: host # Important pour la communication inter-GPU (Pytorch)

volumes:
  hf_cache: