services:
  stt:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: stt:latest
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "5007:5007"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./records:/app/records
      - ./cacheHuggingFace:/root/.cache/huggingface
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - "audio"
    gpus: all
    restart: unless-stopped